### ISSUE TITLE
Unable to find action now that "action" has replaced "service"

### ISSUE THREAD

**Issue by abreingan** [sdaoudi/HomeAssistant-GDrive-Uploader#12]
Hi and thanks for the work putting together this addon. 

I think I have loaded it correctly and the HA log shows it loading at startup as below, but I cannot use it in an automation as gdrive_uploader.upload is not recognised (or any bit of it that I have tried).

I hope I am not doing something stupid, but I suspect it has something to do with the new Actions in scripts and automations.

Thanks again
Al

`2024-10-25 14:59:56.567 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration gdrive_uploader which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

**Comment by sdaoudi** [comment]
Hi Al,

Thank you for your message. From what you describe, it seems that the integration is installed correctly. The warning message you see in the Home Assistant logs is normal, as it is a custom integration and not an official Home Assistant integration.

Could you please check in Developer Tools > Actions if you can see the action gdrive_uploader.upload? This will help us determine if the integration is being recognized correctly.

If you do not see the action, could you provide more logs or details about your configuration? This will allow us to better understand the issue and assist you.

**Comment by abreingan** [comment]
Sorry about the long delay, you answer came as I was on holiday. 
Also while no gdrive actions were present in the Developer Tools > Actions when I tried that previously they are there now and all is well. an extra restart may have helped.
Thanks for the code
