### ISSUE TITLE
credentials

### ISSUE THREAD

**Issue by Gfermoto** [sdaoudi/HomeAssistant-GDrive-Uploader#8]
I received credentials.json but with it HASS does not even reboot. Perhaps I made a mistake in the settings when requesting. Please help me with precise instructions.

**Comment by sdaoudi** [comment]
You can delete the `gdrive_uploader` directly from your filesystem and the restart your home assistant.
You can find this directory in `/config/custom_components`  directory.

To help you make this integration work please provide me with more details of the logs and the steps you followed to generate the credentials.json file.

For info, you can follow this documentation to generate the credentials.json
https://github.com/sdaoudi/HomeAssistant-GDrive-Uploader/blob/main/SERVICE_ACCOUNT.md

**Comment by sdaoudi** [comment]
I published a new version [v1.1.0](https://github.com/sdaoudi/HomeAssistant-GDrive-Uploader/releases/tag/v1.1.0).

- The 2 credentials_file_path and secret_file_path configurations are supported
- The 2 access token and service account formats are supported

This new version should fix all problems. I'll let you create a new ticket if you have any other issues.

Thanks
